export const routesToPrerender: string[] = [
  '/',
  '/cs/home',
  '/cs/about-me',
  '/cs/contact',
  '/cs/services',
  '/cs/tanec-tantra',
  '/cs/pricing',
  '/cs/testimonials',
  '/cs/not-found',
  '/cs/events',

  '/en/home',
  '/en/about-me',
  '/en/contact',
  '/en/services',
  '/en/tanec-tantra',
  '/en/pricing',
  '/en/testimonials',
  '/en/not-found',
  '/en/events',
];
